/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.dc.bco.coma.dem.binding.openhab.util.configgen.jp;

import org.dc.jps.core.JPService;
import org.dc.jps.exception.JPNotAvailableException;
import org.dc.jps.preset.AbstractJPFile;
import org.dc.jps.tools.FileHandler;
import java.io.File;

/**
 *
 * @author mpohling
 */
public class JPOpenHABItemConfig extends AbstractJPFile {
    private static final String[] COMMAND_IDENTIFIERS = {"--item-config"};

    public JPOpenHABItemConfig() {
        super(COMMAND_IDENTIFIERS, FileHandler.ExistenceHandling.Must, FileHandler.AutoMode.On);
    }

    @Override
    protected File getPropertyDefaultValue() throws JPNotAvailableException {
        return new File(new File(JPService.getProperty(JPOpenHABConfiguration.class).getValue(), "items"), "dal-generated.items");
    }

    @Override
    public String getDescription() {
        return "Define the openhab item config file which is generated by dal.";
    }

}
