/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.openbase.java-conventions")
}

description = "BCO Authentication Library"


dependencies {
    api("org.openbase:jul.extension.rsb.scope:2.0-SNAPSHOT")
    api("org.openbase:jul.extension.type.processing:2.0-SNAPSHOT")
    api("org.openbase:jul.extension.protobuf:2.0-SNAPSHOT")
    api("org.openbase:jul.pattern.launch:2.0-SNAPSHOT")
}
