/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://mvn.cit-ec.de/nexus/content/repositories/releases/")
    }

    maven {
        url = uri("https://mvn.cit-ec.de/nexus/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://jcenter.bintray.com")
    }

    maven {
        url = uri("https://openhab.jfrog.io/openhab/libs-release")
    }
}

dependencies {
    implementation("org.openbase:bco.dal.control:2.0-SNAPSHOT")
}

group = "org.openbase"
version = "2.0-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_1_8

java {
    withSourcesJar()
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
