/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.citec.csra.dm.view_old.struct;

import de.citec.csra.dm.exception.NotAvailableException;
import de.citec.csra.dm.struct.DeviceConfig;
import java.util.List;
import javax.swing.JTable;

/**
 *
 * @author mpohling
 */
public class DeviceConfigOverviewPanel extends AbstractOverviewPanel<DeviceConfig> {

	/**
	 * Creates new form DeviceClassOverviewPanel
	 */
	public DeviceConfigOverviewPanel() {

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

	@Override
	protected List<DeviceConfig> getContextList() {
		return deviceManager.getDeviceConfigList();
	}

	@Override
	protected String[] getContextLables() {
		String[] contextLables = {"ID","Name", "Class", "DataStreams", "Description"};
		return contextLables;
	}

	@Override
	protected void updateContextData(final DeviceConfig context, final Object[] contextData) {
		contextData[0] = context.getId();
		contextData[1] = context.getName();
		contextData[2] = context.getDeviceClass();
		contextData[3] = context.getDataStreams().size(); //TODO
		contextData[4] = context.getDescription();
	}

	@Override
	protected void remove(final DeviceConfig deviceConfig) {
		deviceManager.removeDeviceConfig(deviceConfig.getId());
	}

	@Override
	protected void edit(final DeviceConfig deviceConfig) {
		DeviceConfigEditorFrame.edit(deviceConfig);
	}

	@Override
	protected void add() {
		DeviceConfig deviceConfig = new DeviceConfig();
		edit(deviceConfig);
	}

	@Override
	protected DeviceConfig getSelection(final JTable contextTable) throws NotAvailableException {
		return deviceManager.getDeviceConfig((String) contextTable.getModel().getValueAt(contextTable.convertRowIndexToModel(contextTable.getSelectedRow()), 0));
	}
}
