/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.openbase.java-conventions")
}

dependencies {
    implementation(project(":bco.registry.lib"))
    implementation("org.openbase:jul.storage:2.0-SNAPSHOT")
}

description = "BCO Registry Template Library"

java {
    withJavadocJar()
}
