/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.openbase.java-conventions")
}

dependencies {
    api(project(":bco.dal.lib"))
    api(project(":bco.dal.remote"))
    api(project(":bco.registry.util"))
    api("org.openbase:jul.pattern.trigger:2.0-SNAPSHOT")
    api("com.influxdb:influxdb-client-java:[1.0,1.1-alpha)")
}

description = "BCO DAL Control"

