/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.openbase.java-conventions")
}

dependencies {
    implementation(project(":bco.dal.lib"))
    implementation(project(":bco.dal.remote"))
    implementation("org.openbase:bco.registry.util:2.0-SNAPSHOT")
    implementation("org.openbase:jul.pattern.trigger:2.0-SNAPSHOT")
    implementation("com.influxdb:influxdb-client-java:[1.0,1.1-alpha)")
}

description = "BCO DAL Control"

java {
    withJavadocJar()
}
