rootProject.name = "bco"
include("authentication")
include("registry")
include("dal")
include("device")

include(":bco.authentication.test")
include(":bco.authentication.lib")
include(":bco.authentication.core")

include(":bco.registry.template.test")
include(":bco.registry.message.remote")
include(":bco.registry.message.lib")
include(":bco.registry.message")
include(":bco.registry.util")
include(":bco.registry.template.remote")
include(":bco.registry.unit")
include(":bco.registry.activity.core")
include(":bco.registry.activity.test")
include(":bco.registry.remote")
include(":bco.registry.lib")
include(":bco.registry.unit.lib")
include(":bco.registry.unit.core")
include(":bco.registry.template")
include(":bco.registry.message.core")
include(":bco.registry.template.core")
include(":bco.registry.class.core")
include(":bco.registry.class.lib")
include(":bco.registry.class")
include(":bco.registry.unit.test")
include(":bco.registry.activity.lib")
include(":bco.registry.class.remote")
include(":bco.registry.activity.remote")
include(":bco.registry.unit.remote")
include(":bco.registry.message.test")
include(":bco.registry.template.lib")
include(":bco.registry.class.test")
include(":bco.registry.activity")

include(":bco.dal.task")
include(":bco.dal.remote")
include(":bco.dal.example")
include(":bco.dal.control")
include(":bco.dal.lib")
include(":bco.dal.visual")
include(":bco.dal.test")

include(":bco.api.graphql")

include(":bco.app.util")
include(":bco.app.manager")
include(":bco.app.preset")
include(":bco.app.cloud.connector")
include(":bco.app.influxdb.connector")
include(":bco.app.test")

include(":bco.device.openhab")

project(":bco.authentication.test").projectDir = file("authentication/test")
project(":bco.authentication.lib").projectDir = file("authentication/lib")
project(":bco.authentication.core").projectDir = file("authentication/core")

project(":bco.registry.template.test").projectDir = file("registry/template-registry/test")
project(":bco.registry.message.remote").projectDir = file("registry/message-registry/remote")
project(":bco.registry.message.lib").projectDir = file("registry/message-registry/lib")
project(":bco.registry.message").projectDir = file("registry/message-registry")
project(":bco.registry.util").projectDir = file("registry/util")
project(":bco.registry.template.remote").projectDir = file("registry/template-registry/remote")
project(":bco.registry.unit").projectDir = file("registry/unit-registry")
project(":bco.registry.activity.core").projectDir = file("registry/activity-registry/core")
project(":bco.registry.activity.test").projectDir = file("registry/activity-registry/test")
project(":bco.registry.remote").projectDir = file("registry/remote")
project(":bco.registry.lib").projectDir = file("registry/lib")
project(":bco.registry.unit.lib").projectDir = file("registry/unit-registry/lib")
project(":bco.registry.unit.core").projectDir = file("registry/unit-registry/core")
project(":bco.registry.template").projectDir = file("registry/template-registry")
project(":bco.registry.message.core").projectDir = file("registry/message-registry/core")
project(":bco.registry.template.core").projectDir = file("registry/template-registry/core")
project(":bco.registry.class.core").projectDir = file("registry/class-registry/core")
project(":bco.registry.class.lib").projectDir = file("registry/class-registry/lib")
project(":bco.registry.class").projectDir = file("registry/class-registry")
project(":bco.registry.unit.test").projectDir = file("registry/unit-registry/test")
project(":bco.registry.activity.lib").projectDir = file("registry/activity-registry/lib")
project(":bco.registry.class.remote").projectDir = file("registry/class-registry/remote")
project(":bco.registry.activity.remote").projectDir = file("registry/activity-registry/remote")
project(":bco.registry.unit.remote").projectDir = file("registry/unit-registry/remote")
project(":bco.registry.message.test").projectDir = file("registry/message-registry/test")
project(":bco.registry.template.lib").projectDir = file("registry/template-registry/lib")
project(":bco.registry.class.test").projectDir = file("registry/class-registry/test")
project(":bco.registry.activity").projectDir = file("registry/activity-registry")

project(":bco.dal.task").projectDir = file("dal/task")
project(":bco.dal.remote").projectDir = file("dal/remote")
project(":bco.dal.example").projectDir = file("dal/example")
project(":bco.dal.control").projectDir = file("dal/control")
project(":bco.dal.lib").projectDir = file("dal/lib")
project(":bco.dal.visual").projectDir = file("dal/visual")
project(":bco.dal.test").projectDir = file("dal/test")

project(":bco.api.graphql").projectDir = file("api/graphql")

project(":bco.app.manager").projectDir = file("app/manager")
project(":bco.app.util").projectDir = file("app/util")
project(":bco.app.preset").projectDir = file("app/preset")
project(":bco.app.cloud.connector").projectDir = file("app/cloudconnector")
project(":bco.app.influxdb.connector").projectDir = file("app/influxdbconnector")
project(":bco.app.test").projectDir = file("app/test")

project(":bco.device.openhab").projectDir = file("device/openhab")
