/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "bco.dal"
include(":bco.dal.task")
include(":bco.dal.remote")
include(":bco.dal.example")
include(":bco.dal.control")
include(":bco.dal.lib")
include(":bco.dal.visual")
include(":bco.dal.test")
project(":bco.dal.task").projectDir = file("task")
project(":bco.dal.remote").projectDir = file("remote")
project(":bco.dal.example").projectDir = file("example")
project(":bco.dal.control").projectDir = file("control")
project(":bco.dal.lib").projectDir = file("lib")
project(":bco.dal.visual").projectDir = file("visual")
project(":bco.dal.test").projectDir = file("test")
