/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.openbase.java-conventions")
}

dependencies {
    implementation(project(":bco.registry.lib"))
    implementation(project(":bco.registry.activity.remote"))
    implementation(project(":bco.registry.class.remote"))
    implementation(project(":bco.registry.template.remote"))
    implementation(project(":bco.registry.unit.remote"))
    implementation(project(":bco.registry.message.remote"))
    testImplementation("org.junit.jupiter:junit-jupiter-api:[5.6,5.7-alpha)")
    testImplementation("org.junit.vintage:junit-vintage-engine:[5.6,5.7-alpha)")
}

description = "BCO Registry Remote"

java {
    withJavadocJar()
}
