/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.openbase.java-conventions")
}

dependencies {
    api(project(":bco.dal.control"))
    api(project(":bco.app.openapiserver"))
    testImplementation(project(":bco.app.test"))
}

description = "BCO OpenAPI Server"

