/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.openbase.java-conventions")
}

dependencies {
    implementation("org.openbase:bco.dal.control:2.0-SNAPSHOT")
    implementation("org.openbase:bco.openapi:2.0-SNAPSHOT")
    testImplementation(project(":bco.app.test"))
}

description = "BCO OpenAPI Server"

java {
    withJavadocJar()
}
