/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.openbase.bco")
}

dependencies {
    api("org.openbase:jul.storage:2.0-SNAPSHOT")
    api("org.openbase:jul.pattern.launch:2.0-SNAPSHOT")
    api(project(":bco.authentication.lib"))
    api("org.openbase:jul.extension.type.util:2.0-SNAPSHOT")
    api("org.openbase:jul.communication.controller:2.0-SNAPSHOT")
    api("org.openbase:jul.exception:2.0-SNAPSHOT")
    testImplementation("org.junit.jupiter:junit-jupiter-api:[5.6,5.7-alpha)")
    testImplementation("org.junit.vintage:junit-vintage-engine:[5.6,5.7-alpha)")
}

description = "BCO Registry Lib"

