/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.openbase.bco")
}

dependencies {
    api(project(":bco.authentication.core"))
    api(project(":bco.authentication.lib"))
    api("org.testcontainers:testcontainers:1.16.2")
}

description = "BCO Authentication Test"

