/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.openbase.java-conventions")
}

dependencies {
    api(project(":bco.registry.lib"))
    api(project(":bco.registry.unit.remote"))
}

description = "BCO Registry Message Library"

