/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.openbase.bco")
    application
}

repositories {
    maven {
        url = uri("https://openhab.jfrog.io/openhab/libs-release")
    }
    jcenter()
}

application {
    mainClass.set("org.openbase.bco.app.util.launch.BCOLauncher")
}

fun createAdditionalScript(name: String, configureStartScripts: CreateStartScripts.() -> Unit) =
    tasks.register<CreateStartScripts>("startScripts$name") {
        configureStartScripts()
        applicationName = name
        outputDir = File(project.buildDir, "scripts")
        classpath = tasks.getByName("jar").outputs.files + configurations.runtimeClasspath.get()
    }.also {
        application.applicationDistribution.into("bin") {
            from(it)
            //fileMode = 0b000_111_101_101
            duplicatesStrategy = DuplicatesStrategy.EXCLUDE
        }
    }

createAdditionalScript("bco-logo") {
    mainClass.set("org.openbase.bco.app.util.launch.LogoPrinter")
}

createAdditionalScript("bco-manager") {
    mainClass.set("org.openbase.bco.app.util.launch.ManagerLauncher")
}

createAdditionalScript("bco-test") {
    mainClass.set("org.openbase.bco.app.util.launch.BCOTestLauncher")
}

createAdditionalScript("bco-print-api") {
    mainClass.set("org.openbase.bco.app.util.launch.BCOInterfacePrinter")
}

createAdditionalScript("bco-validate") {
    mainClass.set("org.openbase.bco.app.util.launch.BCOSystemValidator")
}

createAdditionalScript("bco-registry-validate") {
    mainClass.set("org.openbase.bco.app.util.launch.BCORegistryValidator")
}

createAdditionalScript("bco-app-adhoc-generate-trainingdata") {
    mainClass.set("org.openbase.bco.app.util.launch.BCOTrainDataGeneratorLauncher")
}

createAdditionalScript("bco-console") {
    mainClass.set("org.openbase.bco.app.util.launch.BCOConsole")
}

distributions {
    main {
        distributionBaseName.set("bco")
    }
}


tasks.register("deploy-bco-dist") {
    dependsOn("installDist")
    val bcoDist = System.getenv("BCO_DIST")?:"${System.getenv("HOME")}/usr"
    val mainDist = distributions.getByName("main").distributionBaseName.get()
    copy {
        from(File(project.buildDir, "install/$mainDist"))
        into(bcoDist)
    }
}

application.applicationName = "bco"

dependencies {
    api(project(":bco.registry.util"))
    api(project(":bco.device.openhab"))
    api(project(":bco.app.manager"))
    api(project(":bco.dal.control"))
    api(project(":bco.app.cloud.connector"))
    api(project(":bco.app.influxdb.connector"))
    api(project(":bco.api.graphql"))
    api("commons-collections:commons-collections:3.2.2")
    testImplementation(project(":bco.dal.test"))
    testImplementation("org.junit.jupiter:junit-jupiter:[5.6,5.7-alpha)")
}

description = "BCO App Utility"

tasks.register("testDeploy") {
    dependsOn("installDist")
    //println("Copy to ${System.getenv("HOME")}/local/bco_tmp")
    //println("BCO_DIST: ${BCO_DIST}")
    copy {
        from(File(project.buildDir, "install/bco-test"))
        into("${System.getenv("HOME")}/local/bco_tmp")
    }
}
