/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.openbase.bco")
}

dependencies {
    api(project(":bco.registry.template.core"))
    api(project(":bco.registry.template.remote"))
    testImplementation("org.junit.jupiter:junit-jupiter-api:_")
}

description = "BCO Registry Template Test"

