/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.openbase.java-conventions")
}

dependencies {
    api("org.openbase:bco.registry.util:2.0-SNAPSHOT")
    api(project(":bco.dal.remote"))
    api(project(":bco.dal.control"))
    api(project(":bco.dal.visual"))
    api("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.0")
    testImplementation("org.jetbrains.kotlin:kotlin-test:1.5.0")
}

description = "BCO DAL Test"

