/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.openbase.java-conventions")
}

dependencies {
    api(project(":bco.registry.class.lib"))
    api(project(":bco.registry.template.remote"))
    api("org.openbase:jul.storage:2.0-SNAPSHOT")
}

description = "BCO Registry Class Remote"

