package org.openbase.bco.app.openhab.jp;

import org.openbase.jps.core.JPService;
import org.openbase.jps.exception.JPNotAvailableException;
import org.openbase.jps.preset.AbstractJPFile;
import org.openbase.jps.tools.FileHandler;

import java.io.File;

public class JPOpenHABSitemap extends AbstractJPFile {
    private static final String[] COMMAND_IDENTIFIERS = {"--sitemap"};

    public JPOpenHABSitemap() {
        super(COMMAND_IDENTIFIERS, FileHandler.ExistenceHandling.Must, FileHandler.AutoMode.On);
    }

    @Override
    protected File getPropertyDefaultValue() throws JPNotAvailableException {
        return new File(new File(JPService.getProperty(JPOpenHABConfiguration.class).getValue(), "sitemaps"), "bco.sitemap");
    }

    @Override
    public String getDescription() {
        return "Defines the openhab sitemap config file which should be generated by bco.";
    }

}
