#!/bin/bash

# configure exit on error
#set -e
#set -o pipefail


#!/bin/bash

# configure exit on error
#set -e
#set -o pipefail


# default config
NETWORK_NAME="bco-net"
SPREAD_DOCKER_NAME="spread"
BCO_DOCKER_NAME="bco"
OPENHAB_DOCKER_NAME="openhab"
OPENHAB_RSB_BINDING_DOCKER_NAME="openhab-binding-rsb"


# overwrite default config via config script
if [ -f /etc/bco/config ]; then
    . /etc/bco/config
fi

function stop() {
    if (check-running $BCO_DOCKER_NAME) then
        echo stop bco
        docker stop -t 120 $BCO_DOCKER_NAME
        docker rm $BCO_DOCKER_NAME
    fi
}

function shutdown() {
    echo shutdown
    stop

    if (check-running $BCO_DOCKER_NAME) then
        docker stop -t 120 $BCO_DOCKER_NAME
    fi
    if (check-running $OPENHAB_DOCKER_NAME) then
        docker stop -t 60 $OPENHAB_DOCKER_NAME
    fi
    if (check-running $OPENHAB_RSB_BINDING_DOCKER_NAME) then
        docker kill $OPENHAB_RSB_BINDING_DOCKER_NAME
    fi
    if (check-running $SPREAD_DOCKER_NAME) then
        # Somehow the spread docker does not work with any signals so just kill it
        docker kill $SPREAD_DOCKER_NAME
    fi

    if (check-created $BCO_DOCKER_NAME) then
        docker rm $BCO_DOCKER_NAME
    fi
    if (check-created $OPENHAB_DOCKER_NAME) then
        docker rm $OPENHAB_DOCKER_NAME
    fi
    if (check-created $OPENHAB_RSB_BINDING_DOCKER_NAME) then
        docker rm $OPENHAB_RSB_BINDING_DOCKER_NAME
    fi
    if (check-created $SPREAD_DOCKER_NAME) then
        docker rm $SPREAD_DOCKER_NAME
    fi
}

function restart() {
    stop
    start
}

function check-running {
    docker container ls | grep -q "$1 "
    return $?
}

function check-created {
    docker container ls -a | grep -q "$1 "
}

function check-network() {
    docker network ls | grep -q $NETWORK_NAME
    return $?
}

function check() {
    check-running $SPREAD_DOCKER_NAME
    SPREAD_RUNNING=$?
    check-running $BCO_DOCKER_NAME
    BCO_RUNNING=$?
    check-running $OPENHAB_DOCKER_NAME
    OPENHAB_RUNNING=$?
    check-running $OPENHAB_RSB_BINDING_DOCKER_NAME
    OPENHAB_BINDING_RSB_RUNNING=$?
    if [ $SPREAD_RUNNING == 0 ] && [ $BCO_RUNNING == 0 ] && [ $OPENHAB_RUNNING == 0 ] && [ $OPENHAB_BINDING_RSB_RUNNING == 0 ]
    then
        echo "Running"
        return 0
    elif [ $SPREAD_RUNNING == 1 ] && [ $BCO_RUNNING == 1 ] && [ $OPENHAB_RUNNING == 1 ] && [ $OPENHAB_BINDING_RSB_RUNNING == 1 ]
    then
        echo "Stopped"
        return 1
    else
        echo "At least one component is not running" 
        return 1
    fi
}


function start() {
    
    # Setup network infrastructure
    if ! (check-network) then
        # Create a new docker network to be able to alias hosts
        docker network create $NETWORK_NAME
    fi

    # Start the spread host
    if ! (check-running $SPREAD_DOCKER_NAME) then
        if (check-created $SPREAD_DOCKER_NAME) then
            docker restart $SPREAD_DOCKER_NAME
        else
            docker run -d --name=$SPREAD_DOCKER_NAME -p 4803:4803  --network=$NETWORK_NAME spread
        fi
        # wait so that spread is up and running when bco is started
        sleep 2
    fi

    # Start bco     
    if ! (check-running $BCO_DOCKER_NAME) then
        if (check-created $BCO_DOCKER_NAME) then
            docker restart $BCO_DOCKER_NAME
        else
            docker run -d \
                      --name=$BCO_DOCKER_NAME \
                      --network=$NETWORK_NAME \
                      -v $prefix/var:/usr/local/bco/var \
                      -v $prefix/etc:/usr/local/bco/etc:ro \
                      -v $prefix/share:/usr/local/bco/share:ro \
                      $BCO_DOCKER_NAME
        fi
    fi

    check-running $OPENHAB_DOCKER_NAME
    # Start openhab
    if ! (check-running $OPENHAB_DOCKER_NAME) then
        if (check-created $OPENHAB_DOCKER_NAME) then
            docker restart $OPENHAB_DOCKER_NAME
        else
            docker run -d \
                      --name=$OPENHAB_DOCKER_NAME \
                      --network=$NETWORK_NAME \
                      -v $prefix/var:/usr/local/bco/var \
                      -v $prefix/share/openhab/distribution/configurations:/usr/local/bco/share/openhab/distribution/configurations \
                      -v $prefix/share/openhab/distribution/addons:/usr/local/bco/share/openhab/distribution/addons \
                      $OPENHAB_DOCKER_NAME
        fi
    fi

    # Start openhab-binding-rsb
    if ! (check-running $OPENHAB_RSB_BINDING_DOCKER_NAME) then
        if (check-created $OPENHAB_RSB_BINDING_DOCKER_NAME) then
            docker restart $OPENHAB_RSB_BINDING_DOCKER_NAME
        else
            docker run -d \
                      --name=$OPENHAB_RSB_BINDING_DOCKER_NAME \
                      --network=$NETWORK_NAME \
                      -v $prefix/share:/usr/local/bco/share \
                      $OPENHAB_RSB_BINDING_DOCKER_NAME
        fi
    fi

}

function upgrade() {
    stop
    if ! (check-bco) then
        echo ready to perform the upgrade...
    else
        echo stop failed! Please try again...
        return 1
    fi

    echo start upgrade
    
    # do update
    # docker pull xyz

    start
}

function logo() {
    YEAR=$(date +'%Y')
    clear
    echo "                                 "
    echo "                             "
    echo "     #####    ####  #######      "
    echo "     ##  ##  ##     ##   ##      "
    echo "     #####   ##     ##   ##      "
    echo "     ##  ##  ##     ##   ##      "
    echo "     #####    ####  #######      "
    echo "     ======================      "
    echo ""
    echo "          openbase.org ${YEAR}    "
    echo "                     "
}

function bco-help() {
    
    echo -e "usage:"
    echo -e ""
    echo -e "    bco-launcher [ start | restart | stop | shutdown | check | upgrade | help ]"
    echo -e ""
    echo -e "where:"
    echo -e ""
    echo -e "    start     - starts the bco docker setup"
    echo -e "    restart   - restarts the bco docker setup"
    echo -e "    stop      - stops the bco docker setup"
    echo -e "    shutdown  - stops the bco docker setup and stops the docker middleware and network infrastructure."
    echo -e "    check     - returns 0 if everything is up and running otherwise a number > 0 is returned"
    echo -e "    upgrade   - stops the bco docker, upgrades the container and starts bco after success."
    echo -e "    help      - prints this help page"
    echo ""
}

# print logo
logo

# setup command terminator
eval set -- "$@ --"

# extract options and their arguments into variables.
while true ; do
    case "$1" in

        stop) stop ; shift ;;
        shutdown) shutdown ; shift ;;
        restart) restart ; shift ;;
        check) check ; shift ;;
        start) start ; shift ;;
        upgrade ) upgrade ; shift ;;
        help|-h|--help) bco-help ; exit 1 ;;
        --) shift ; break ;;
        *) echo "unknown command: $1" ; echo ; bco-help ; exit 1 ;;
    esac
done

