version: "3.9"

volumes:
  database_data:
    driver: local
  customer_data:
    driver: local

services:
  mosquitto:
    image: mosquitto
    ports:
      - "1883:1883"
    volumes: $HOME/.mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always
    logging:
      driver: local
    detach: true  


  postgres:
    build: ./postgres
    image: "prodaso/postgres"
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "prodaso"
      POSTGRES_PASSWORD: "iMqU8sJk"
  mailhog:
    build: "mailhog"
    ports:
      - "127.0.0.1:8025:8025"
      - "127.0.0.1:1025:1025"
