/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.dc.bco.manager.scene.visual;

/*
 * #%L
 * COMA SceneManager Visualisation
 * %%
 * Copyright (C) 2015 - 2016 DivineCooperation
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/gpl-3.0.html>.
 * #L%
 */
import com.google.protobuf.Descriptors;
import com.google.protobuf.Message;
import java.awt.Component;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import org.dc.bco.dal.visual.service.AbstractServicePanel;
import org.dc.jul.exception.CouldNotPerformException;
import org.dc.jul.exception.printer.ExceptionPrinter;
import org.dc.jul.exception.printer.LogLevel;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.concurrent.Executors;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import org.dc.bco.dal.visual.unit.GenericUnitPanel;
import org.dc.jul.exception.NotAvailableException;
import org.dc.jul.pattern.Observable;
import org.dc.jul.pattern.Observer;
import org.dc.jul.processing.StringProcessor;
import org.slf4j.LoggerFactory;
import rst.homeautomation.control.action.ActionAuthorityType.ActionAuthority;
import rst.homeautomation.control.action.ActionConfigType.ActionConfig;
import rst.homeautomation.control.action.ActionPriorityType.ActionPriority;
import rst.homeautomation.state.PowerStateType;

/**
 *
 * @author <a href="mailto:thuxohl@techfak.uni-bielefeld.com">Tamino Huxohl</a>
 */
public class DalSceneEditor extends javax.swing.JFrame {
    
    protected static final org.slf4j.Logger logger = LoggerFactory.getLogger(DalSceneEditor.class);

    /**
     * Creates new form DalSceneEditor
     *
     * @throws org.dc.jul.exception.InstantiationException
     */
    public DalSceneEditor() throws org.dc.jul.exception.InstantiationException {
        
        try {
            initComponents();
            sceneSelectorPanel.addObserver(new Observer<SceneSelectorPanel.UnitConfigServiceTypeHolder>() {
                
                @Override
                public void update(Observable<SceneSelectorPanel.UnitConfigServiceTypeHolder> source, SceneSelectorPanel.UnitConfigServiceTypeHolder data) throws Exception {
                    genericUnitCollectionPanel1.add(data.getConfig(), data.getServiceType());
                }
            });
            sceneCreationPanel.init();
            Executors.newSingleThreadExecutor().execute(new Runnable() {
                
                @Override
                public void run() {
                    try {
                        sceneSelectorPanel.init();
                    } catch (Exception ex) {
                        ExceptionPrinter.printHistory(ex, logger, LogLevel.WARN);
                    }
                }
            });
        } catch (Exception ex) {
            ExceptionPrinter.printHistory(ex, logger, LogLevel.WARN);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sceneCreationPanel = new org.dc.bco.manager.scene.visual.SceneCreationPanel();
        sceneSelectorPanel = new org.dc.bco.manager.scene.visual.SceneSelectorPanel();
        genericUnitCollectionPanel1 = new org.dc.bco.dal.visual.unit.GenericUnitCollectionPanel();
        saveButton = new javax.swing.JButton();
        statusPanel1 = new org.dc.bco.dal.visual.util.StatusPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Scene"));

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sceneCreationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sceneSelectorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(genericUnitCollectionPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 103, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statusPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sceneCreationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sceneSelectorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(genericUnitCollectionPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        Collection<GenericUnitPanel> unitPanelList = genericUnitCollectionPanel1.getUnitPanelList();
        List<ActionConfig> actionConfigs = new ArrayList<>();
        for (GenericUnitPanel unitPanel : unitPanelList) {
            List<JComponent> componentList = unitPanel.getComponentList();
            for (JComponent component : componentList) {
                AbstractServicePanel panel = null;
                for (Component com : component.getComponents()) {
                    if (com instanceof AbstractServicePanel) {
                        panel = (AbstractServicePanel) com;
                    }
                }
                if (panel == null) {
                    logger.warn("Panel without service panel?");
                    continue;
                }
                Object value = null;
                try {
                    String methodName = ("get" + StringProcessor.transformUpperCaseToCamelCase(panel.getServiceType().toString())).replaceAll("Service", "");
                    logger.info("Testing method name [" + methodName + "] with class [" + panel.getService().getClass().getSimpleName() + "]");
                    Method method = panel.getService().getClass().getMethod(methodName);
                    value = method.invoke(panel.getService());
                } catch (NotAvailableException | NoSuchMethodException | SecurityException | IllegalAccessException | IllegalArgumentException | InvocationTargetException ex) {
                    Logger.getLogger(DalSceneEditor.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (value == null) {
                    logger.warn("Value null for unit service [" + panel.getUnitId() + " " + panel.getServiceType() + "] therefore continue!");
                    continue;
                }
                logger.info("Got value [" + value + "]");
                ActionConfig.Builder actionConfig = ActionConfig.newBuilder().setServiceType(panel.getServiceType()).setServiceHolder(panel.getUnitId());
                if (value instanceof Message) {
//                    if (((Message) value).getDescriptorForType()) {
//                        logger.info("EnumValueDescriptor value received [" + ((Descriptors.EnumValueDescriptor) value).getName() + "] string [" + value.toString() + "]!");
//                    }
//                    PowerStateType.PowerState.State
//                    logger.info("Message value with type [" + value.getClass().getSimpleName() + "]");
                    actionConfig.setServiceAttributeBytes(((Message) value).toByteString());
                } else {
                    if (value instanceof Enum) {
                        logger.info("Enum value received [" + ((Enum) value).name() + "] string [" + value.toString() + "]!");
                    }
                    actionConfig.setServiceAttribute(value.toString());
                }
                actionConfig.setActionAuthority(ActionAuthority.newBuilder().setAuthority(ActionAuthority.Authority.USER)).setActionPriority(ActionPriority.newBuilder().setPriority(ActionPriority.Priority.NORMAL));
                actionConfigs.add(actionConfig.build());
            }
        }
        try {
            sceneCreationPanel.updateSceneConfig(actionConfigs);
        } catch (CouldNotPerformException ex) {
            ExceptionPrinter.printHistory(ex, logger, LogLevel.WARN);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DalSceneEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DalSceneEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DalSceneEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DalSceneEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DalSceneEditor().setVisible(true);
                } catch (org.dc.jul.exception.InstantiationException ex) {
                    ExceptionPrinter.printHistory(ex, logger, LogLevel.ERROR);
                    System.exit(1);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.dc.bco.dal.visual.unit.GenericUnitCollectionPanel genericUnitCollectionPanel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton saveButton;
    private org.dc.bco.manager.scene.visual.SceneCreationPanel sceneCreationPanel;
    private org.dc.bco.manager.scene.visual.SceneSelectorPanel sceneSelectorPanel;
    private org.dc.bco.dal.visual.util.StatusPanel statusPanel1;
    // End of variables declaration//GEN-END:variables
}
