/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.openbase.java-conventions")
}

dependencies {
    api("org.openbase:jul.storage:2.0-SNAPSHOT")
    api(project(":bco.registry.lib"))
}

description = "BCO Registry Activity Library"

