/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.openbase.bco")
}

dependencies {
    api(project(":bco.registry.unit.lib"))
    api("org.openbase:jul.extension.type.processing:2.0-SNAPSHOT")
    api("org.openbase:jul.extension.type.storage:2.0-SNAPSHOT")
    api("org.openbase:jul.processing:2.0-SNAPSHOT")
    api(project(":bco.authentication.core"))
}

description = "BCO Registry Unit Core"

