/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.openbase.java-conventions")
}

dependencies {
    implementation(project(":bco.registry.class.lib"))
    implementation(project(":bco.registry.template.remote"))
    implementation("org.openbase:jul.extension.rsb.scope:2.0-SNAPSHOT")
    implementation("org.openbase:jul.extension.type.processing:2.0-SNAPSHOT")
    implementation("org.openbase:jul.extension.type.storage:2.0-SNAPSHOT")
    implementation("org.openbase:jul.processing:2.0-SNAPSHOT")
}

description = "BCO Registry Class Core"

java {
    withJavadocJar()
}
