/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.openbase.java-conventions")
}

dependencies {
    implementation(project(":bco.authentication.lib"))
}

description = "BCO Authentication Core"

java {
    withJavadocJar()
}
