/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.openbase.java-conventions")
}

dependencies {
    api(project(":bco.dal.remote"))
    api("org.openbase:jul.visual.javafx:2.0-SNAPSHOT")
    api("org.openbase:jul.visual.swing:2.0-SNAPSHOT")
}

description = "BCO DAL Visualisation"

