/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.openbase.java-conventions")
}

dependencies {
    implementation("org.openbase:jul.storage:2.0-SNAPSHOT")
    implementation("org.openbase:rct:[0.18,0.19-alpha)")
    implementation(project(":bco.registry.lib"))
    implementation(project(":bco.registry.class.remote"))
    implementation(project(":bco.registry.template.remote"))
    implementation(project(":bco.registry.activity.remote"))
    implementation("org.apache.commons:commons-math3:3.6.1")
}

description = "BCO Registry Unit Library"

java {
    withJavadocJar()
}
