/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.unibi.csra.dm.view.struct;

import de.unibi.csra.dm.exception.NotAvailableException;
import de.unibi.csra.dm.struct.DataStream;
import java.util.List;
import javax.swing.JTable;

/**
 *
 * @author mpohling
 */
public class DataStreamOverviewPanel extends AbstractOverviewPanel<DataStream> {

	/**
	 * Creates new form DeviceClassOverviewPanel
	 */
	public DataStreamOverviewPanel() {

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

	@Override
	protected List<DataStream> getContextList() {
		return deviceManager.getDataStreamList();
	}

	@Override
	protected String[] getContextLables() {
		String[] contextLables = {"ID","Name", "RST-Type", "DataSize", "Frequency", "MetaAttributeMap", "Description"};
		return contextLables;
	}

	@Override
	protected void updateContextData(final DataStream context, final Object[] contextData) {
		contextData[0] = context.getId();
		contextData[1] = context.getName();
		contextData[2] = context.getRst_type();
		contextData[3] = context.getDataSize();
		contextData[4] = context.getFrequency();
		contextData[5] = context.getMetaAttributeMap();
		contextData[6] = context.getDescription();
	}

	@Override
	protected void remove(final DataStream dataStream) {
		deviceManager.removeDataStream(dataStream.getId());
	}

	@Override
	protected void edit(final DataStream dataStream) {
		DataStreamEditorFrame.edit(dataStream);
	}

	@Override
	protected void add() {
		DataStream dataStream = new DataStream();
		edit(dataStream);
	}

	@Override
	protected DataStream getSelection(final JTable contextTable) throws NotAvailableException {
		return deviceManager.getDataStream((String) contextTable.getModel().getValueAt(contextTable.getSelectedRow(), 0));
	}
}
