/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.unibi.csra.dm.view.struct;

import de.unibi.csra.dm.exception.InvalidOperationException;
import de.unibi.csra.dm.exception.NotAvailableException;
import de.unibi.csra.dm.struct.DeviceInstance;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author mpohling
 */
public class DeviceInstanceEditorFrame extends AbstractEditorFrame<DeviceInstance> {

	private final JTextField name, serialNumber;
	private final JTextArea description;
	private final JComboBox deviceClass, status;
	private final LocationEditorPanel location;
	
	protected static Map<String, DeviceInstanceEditorFrame> editorInstances = new HashMap<String, DeviceInstanceEditorFrame>();
	
	public static synchronized void edit(DeviceInstance deviceInstance) {
		String contextKey = deviceInstance.getId();
		if (!editorInstances.containsKey(contextKey)) {
			editorInstances.put(contextKey, new DeviceInstanceEditorFrame());
		}
		editorInstances.get(contextKey).init(deviceInstance);
	}

	/**
	 * Creates new form DeviceInstanceEditorPanel
	 */
	public DeviceInstanceEditorFrame() {
		this.name = new JTextField();
		this.serialNumber = new JTextField();
		this.description = new JTextArea();
		this.deviceClass = new JComboBox();
		this.status = new JComboBox(DeviceInstance.DeviceStatus.values());
		this.location = new LocationEditorPanel();

		addContextElement("Name", name);
		addContextElement("SerialNumber", serialNumber);
		addContextElement("DeviceClass", deviceClass);
		addContextElement("Status", status);
		addContextElement("DeviceLocation", location);
		addContextElement("Description", description);
		pack();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
	@Override
	protected void load(final DeviceInstance context) {
		name.setText(context.getName());
		serialNumber.setText(context.getSerialNumber());
		description.setText(context.getDescription());
		deviceClass.setModel(new DefaultComboBoxModel(deviceManager.getDeviceClassMap().keySet().toArray()));
		deviceClass.setSelectedItem(context.getDeviceClass());
		status.setSelectedItem(context.getStatus());
		location.load(context.getLocation());
	}

	@Override
	protected void save(final DeviceInstance context) throws InvalidOperationException {
		context.setName(name.getText());
		context.setSerialNumber(serialNumber.getText());
		context.setDescription(description.getText());
		context.setDeviceClass((String) deviceClass.getSelectedItem());
		context.setStatus((DeviceInstance.DeviceStatus) status.getSelectedItem());
		location.save();
		context.updateID();
		deviceManager.addDeviceInstance(context);
	}

	@Override
	protected boolean checkExistence(final DeviceInstance context) throws NotAvailableException {
		return deviceManager.getDeviceInstance(context.getId()) != null;
	}

	@Override
	protected void enableKeyContext(final boolean enabled) {
		deviceClass.setEnabled(enabled);
		name.setEnabled(enabled);
	}
}
