/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.unibi.csra.dm.view.struct;

import de.unibi.csra.dm.exception.InvalidOperationException;
import de.unibi.csra.dm.exception.NotAvailableException;
import de.unibi.csra.dm.struct.DeviceClass;
import de.unibi.csra.dm.view.components.DataStreamSelectionTable;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author mpohling
 */
public class DeviceClassEditorFrame extends AbstractEditorFrame<DeviceClass> {

	private final JTextField name, productNumber;
	private final DataStreamSelectionTable dataStreams;
	private final JTextArea description;

	protected final static Map<String, DeviceClassEditorFrame> editorInstances = new HashMap<String, DeviceClassEditorFrame>();

	public static synchronized void edit(final DeviceClass deviceClass) {
		String contextKey = deviceClass.getId();
		if (!editorInstances.containsKey(contextKey)) {
			editorInstances.put(contextKey, new DeviceClassEditorFrame());
		}
		editorInstances.get(contextKey).init(deviceClass);
	}

	/**
	 * Creates new form DeviceClassEditorPanel
	 */
	public DeviceClassEditorFrame() {
		this.name = new JTextField();
		this.productNumber = new JTextField();
		this.dataStreams = new DataStreamSelectionTable();
		this.description = new JTextArea();

		addContextElement("Name", name);
		addContextElement("ProductNumber", productNumber);
		addContextElement("SupportedDataStreams", dataStreams);
		addContextElement("Description", description);
		pack();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
	@Override
	protected void load(final DeviceClass context) {
		name.setText(context.getName());
		productNumber.setText(context.getProductNumber());
		description.setText(context.getDescription());
		dataStreams.load(context.getSupportedDataStreams(), deviceManager.getDataStreamMap().keySet());
	}

	@Override
	protected void save(final DeviceClass context) throws InvalidOperationException {
		context.setName(name.getText());
		context.setProductNumber(productNumber.getText());
		context.setDescription(description.getText());
		context.setSupportedDataStreams(dataStreams.getDataStreamSelectionList());
		context.updateID();
		deviceManager.addDeviceClass(context);
	}

	@Override
	protected boolean checkExistence(final DeviceClass context) throws NotAvailableException {
		return deviceManager.getDeviceClass(context.getId()) != null;
	}

	@Override
	protected void enableKeyContext(final boolean enabled) {
		name.setEnabled(enabled);
	}
}
