/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package de.unibi.csra.dm.view.struct;

import de.unibi.csra.dm.struct.DeviceLocation;

/**
 *
 * @author mpohling
 */
public final class LocationEditorPanel extends javax.swing.JPanel {
	
	private DeviceLocation location;

	/**
	 * Creates new form LocationEditorPanel
	 */
	public LocationEditorPanel() {
		this.initComponents();
		this.locationTable.getTableHeader().setReorderingAllowed(false);
		this.updateDynamicComponents();
	}
	
	public void updateDynamicComponents() {
		boolean locationRegistered = location != null;
		
		locationTable.setEnabled(locationRegistered);
		descriptionTextArea.setEnabled(locationRegistered);
	}
	
	public void load(final DeviceLocation location) {
		this.location = location;
		locationTable.setValueAt(location.getPosition()[0], 0, 0);
		locationTable.setValueAt(location.getPosition()[1], 1, 0);
		locationTable.setValueAt(location.getPosition()[2], 2, 0);
		
		locationTable.setValueAt(location.getRotation()[0], 0, 1);
		locationTable.setValueAt(location.getRotation()[1], 1, 1);
		locationTable.setValueAt(location.getRotation()[2], 2, 1);
		descriptionTextArea.setText(location.getDescription());
		
		updateDynamicComponents();
	}
	
	public void save() {
		
		location.getPosition()[0] = (Double) locationTable.getValueAt(0, 0);
		location.getPosition()[1] = (Double) locationTable.getValueAt(1, 0);
		location.getPosition()[2] = (Double) locationTable.getValueAt(2, 0);
		
		location.getRotation()[0] = (Double) locationTable.getValueAt(0, 1);
		location.getRotation()[1] = (Double) locationTable.getValueAt(1, 1);
		location.getRotation()[2] = (Double) locationTable.getValueAt(2, 1);

		location.setDescription(descriptionTextArea.getText());
		
		location = null;
		updateDynamicComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        locationTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Location"));

        jLabel3.setText("Description");

        locationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Position (x,y,z)", "Rotation (α,β,ɣ)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        locationTable.setOpaque(false);
        locationTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(locationTable);

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(5);
        jScrollPane2.setViewportView(descriptionTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable locationTable;
    // End of variables declaration//GEN-END:variables
}
