/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.openbase.java-conventions")
}

dependencies {
    api("org.openbase:bco.dal.control:2.0-SNAPSHOT")
    api(project(":bco.app.preset"))
    api(project(":bco.app.cloud.connector"))
}

description = "BCO App Manager"

