/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.openbase.java-conventions")
}

dependencies {
    implementation("org.openbase:bco.dal.control:2.0-SNAPSHOT")
    implementation(project(":bco.app.preset"))
    implementation(project(":bco.app.cloud.connector"))
}

description = "BCO App Manager"

java {
    withJavadocJar()
}
