/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.openbase.java-conventions")
}

dependencies {
    api(project(":bco.authentication.core"))
    api(project(":bco.authentication.lib"))
}

description = "BCO Authentication Test"

