/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.openbase.java-conventions")
}

dependencies {
    implementation("org.glassfish.jersey.core:jersey-client:2.31")
    implementation("org.glassfish.jersey.inject:jersey-hk2:2.31")
    implementation("org.glassfish.jersey.media:jersey-media-sse:2.31")
    implementation("org.openhab.core.bundles:org.openhab.core.io.rest.core:2.5.0")
}

description = "BCO Openhab Device Manager"

java {
    withJavadocJar()
}
