/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package de.citec.csra.rsbbindingtester.view;

/**
 *
 * @author nuc
 */
public class MotionSensorPanel extends javax.swing.JPanel {

    /**
     * Creates new form MotionSensorPanel
     */
    public MotionSensorPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scopePanel1 = new de.citec.csra.rsbbindingtester.view.ScopePanel();
        motionStatePanel = new javax.swing.JPanel();
        motionStateLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Motion Sensor"));

        motionStateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        motionStateLabel.setText("Unknown");

        javax.swing.GroupLayout motionStatePanelLayout = new javax.swing.GroupLayout(motionStatePanel);
        motionStatePanel.setLayout(motionStatePanelLayout);
        motionStatePanelLayout.setHorizontalGroup(
            motionStatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(motionStatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(motionStateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        motionStatePanelLayout.setVerticalGroup(
            motionStatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(motionStatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(motionStateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(motionStatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(scopePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scopePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(motionStatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel motionStateLabel;
    private javax.swing.JPanel motionStatePanel;
    private de.citec.csra.rsbbindingtester.view.ScopePanel scopePanel1;
    // End of variables declaration//GEN-END:variables
}
