/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.openbase.java-conventions")
}

dependencies {
    implementation("org.openbase:bco.registry.util:2.0-SNAPSHOT")
    implementation("org.openbase:bco.device.openhab:2.0-SNAPSHOT")
    implementation(project(":bco.app.manager"))
    implementation("org.openbase:bco.dal.control:2.0-SNAPSHOT")
    implementation(project(":bco.app.cloud.connector"))
    implementation(project(":bco.app.influxdb.connector"))
    implementation("org.openbase:bco.api.graphql:2.0-SNAPSHOT")
    implementation("commons-collections:commons-collections:3.2.2")
    testImplementation("org.openbase:bco.dal.test:2.0-SNAPSHOT")
    testImplementation("org.junit.jupiter:junit-jupiter:[5.6,5.7-alpha)")
}

description = "BCO App Utility"

java {
    withJavadocJar()
}
