/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.openbase.java-conventions")
}

dependencies {
    api("org.openbase:bco.dal.test:2.0-SNAPSHOT")
}

description = "BCO App Test Framework"

