/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "bco.authentication"
include(":bco.authentication.test")
include(":bco.authentication.lib")
include(":bco.authentication.core")
project(":bco.authentication.test").projectDir = file("test")
project(":bco.authentication.lib").projectDir = file("lib")
project(":bco.authentication.core").projectDir = file("core")
